# Plotting python file to plot the Magnitization and the Chi values
# Author Miles Bethel (miles.d.bethel@gmail.com)
# Date Modified: 04/01/2026

import matplotlib.pyplot as plt          # Required for plotting the graphs
from scipy.stats import linregress       # Required to perform the linear regression (line of best fit)
import numpy as np                       # Required for math operations like natural log (np.log)
import pandas as pd                      # Required for reading the CSV data into a dataframe

# Load the simulation data generated by the C++ code into a Pandas DataFrame
data = pd.read_csv("ising_data.csv")

# Manually define the critical temperature (extracted from the C++ output)
Tc = 2.27 

# Filter the dataset to only include temperatures slightly below the critical point.
# This range (1.67 to Tc - 0.02) isolates the area where the power law approximation holds true.
fit_data = data[(data['Temperature'] >= 1.67) & (data['Temperature'] < Tc - 0.02)].copy()

# Apply the natural logarithm to both sides of the power law equation to linearize it.
# We are converting M ~ (Tc - T)^beta into ln(M) = beta * ln(Tc - T) + C
fit_data['ln_dT'] = np.log(Tc - fit_data['Temperature']) # Calculate X-axis for linear regression
fit_data['ln_M'] = np.log(fit_data['Magnetization'])     # Calculate Y-axis for linear regression

# Perform a linear regression on the logged data. 
# The function returns multiple values, but we only want the slope ([0]), which equals Beta.
beta = linregress(fit_data['ln_dT'], fit_data['ln_M'])[0]

# Create a scatter plot of Magnetization vs Temperature using the main dataset
plt.scatter(data["Temperature"], data['Magnetization'], color= "purple", label = "Magnetization", s = 30)

# Overlay a line plot of the Susceptibility (Chi) vs Temperature on the same graph
plt.plot(data["Temperature"], data['Chi'] ,color= "red", label = "Chi 10^2")

# Add a title to the graph
plt.title('3D Ising Model: Second Order Phase Transition as a function of Temp')
# Label the X-axis
plt.xlabel("Temperature (J/k_b)")

# Add a floating text box to the graph displaying the calculated Beta value.
# transform=plt.gca().transAxes anchors the text relative to the graph size (0.64 is 64% from left, 0.82 is 82% from bottom)
plt.text(0.64, 0.82, f"Calculated Beta: {beta:.4f}", transform=plt.gca().transAxes,
         fontsize=10, verticalalignment='top',
         bbox=dict(boxstyle='round,pad=0.5', 
                   facecolor='white', edgecolor='gray', alpha=0.8))

# Add a grid to make reading values easier, with 60% opacity (alpha = 0.6)
plt.grid(True, alpha = 0.6)
# Add a legend based on the 'label' attributes set in the scatter/plot functions
plt.legend()

# Save the generated figure as a PNG image file
plt.savefig('ising_transition.png')
# Display the graph in a pop-up window
plt.show()